export interface empresa {
    fk_id_cobertura: number,
    fk_id_estat_empresa: number,
    id_empresa: number,
    rfc: string,
    descripcion_oferta_valor: string,
    facebook: string,
    instagram: string,
    web: string,
    twitter: string,
    linkedin: string,
    nombre: string,
    principales_clientes: string,
    razon_social: string,
    sectores_atendidos: string,
    fecha_creacion: string,
}